language: node_js
sudo: false
node_js:
  - node
  - lts/*
notifications:
  email:
    on_success: "never"
install:
  - npm ci
script:
  - "npm run lint"
  - "npm run bootstrap"
  - "npm run cover"
  - "npm run combine-coverage"
  - "npm run coveralls"
