language: node_js
sudo: false
node_js:
  - 10
  - 8
  - 6
notifications:
  email:
    on_success: "never"
script:
  - "npm run lint"
  - "./bin/test"
  - "npm run combine-coverage"
  - "npm run coveralls"
