language: node_js
sudo: false
node_js:
  - "8.0"
  - "7.0"
  - "6.0"
  - "5.0"
  - "4.0"
notifications:
  email:
    on_success: "never"
script:
  - "./bin/test"
  - "npm run combine-coverage"
  - "npm run coveralls"
