language: node_js
sudo: false
os:
  - linux
  - windows
node_js:
  - 10
  - 8
notifications:
  email:
    on_success: "never"
install:
  - npm ci
script:
  - "npm run lint"
  - "./bin/test"
  - "npm run combine-coverage"
  - "npm run coveralls"
